name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Запуск раз в сутки
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: profile
          sparse-checkout-cone-mode: only

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Copy snake files to profile
        run: |
          mkdir -p profile
          cp dist/snake.svg profile/snake.svg
          cp dist/snake-dark.svg profile/snake-dark.svg

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add/update snake animation"
          file_pattern: "profile/*.svg"
